# Generated by Django 2.2.1 on 2019-10-04 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atribut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_audio', models.CharField(max_length=2048)),
                ('id_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LinkAtribut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('displayLink', models.CharField(max_length=255)),
                ('displayLink_audio', models.CharField(max_length=1024)),
                ('displayLink_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('title_audio', models.CharField(max_length=1024)),
                ('title_id', models.CharField(max_length=255)),
                ('snippet', models.CharField(max_length=255)),
                ('snippet_audio', models.CharField(max_length=1024)),
                ('snippet_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('path_audio', models.CharField(max_length=2048)),
                ('id_description', models.CharField(max_length=255)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='makevisio.Atribut')),
            ],
        ),
    ]
