# Generated by Django 2.2.1 on 2019-06-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atribut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_audio', models.CharField(max_length=2048)),
                ('id_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('path_audio', models.CharField(max_length=2048)),
                ('id_description', models.CharField(max_length=255)),
            ],
        ),
    ]
