# Generated by Django 2.2.1 on 2019-10-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makevisio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='opt_link',
            field=models.CharField(default='nolink', max_length=512),
        ),
    ]
