# Generated by Django 2.2.1 on 2019-06-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makevisio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkAtribut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('displayLink', models.CharField(max_length=255)),
                ('displayLink_audio', models.CharField(max_length=1024)),
                ('displayLink_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('title_audio', models.CharField(max_length=1024)),
                ('title_id', models.CharField(max_length=255)),
                ('snippet', models.CharField(max_length=255)),
                ('snippet_audio', models.CharField(max_length=1024)),
                ('snippet_id', models.CharField(max_length=255)),
            ],
        ),
    ]
