# Generated by Django 2.2.1 on 2019-10-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makevisio', '0002_item_opt_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atribut',
            name='name',
            field=models.CharField(max_length=2048),
        ),
    ]
