# Generated by Django 2.2.1 on 2019-10-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makevisio', '0003_auto_20191020_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='opt_link',
            field=models.CharField(default='nolink', max_length=2048),
        ),
    ]
